baseURL = '#'
languageCode = 'gl-es'
title = 'Arco Teo'
theme = 'lightbi-hugo'

enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"


[params]
rss = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false

previewCardImagePlacement = "top"
selfHosted = true
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description="Clube de Tiro con Arco de Teo."

   
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"