baseURL = '#'
languageCode = 'gl-es'
title = 'ArcoTeo'
theme = 'lightbi-hugo'

enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[params]
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false

keywords = [
    "arco recurvo en Teo",
    "arco recurvo en Santiago",
    "arco recurvo en Santiago de Compostela",
    "arco olímpico en Teo",
    "arco olímpico en Santiago",
    "arco olímpico en Santiago de Compostela",
    "tiro con arco en Teo",
    "tiro con arco en Santiago",
    "tiro con arco en Santiago de Compostela",
    "tiro con arco en Galicia",
    "tiro con arco olímpico",
    "como practicar tiro con arco en Teo",
    "como practicar tiro con arco en Santiago",
    "como practicar tiro con arco en Santiago de Compostela",
    "arcos recurvos para principiantes en Santiago",
    "arcos deportivos en Santiago de Compostela",
    "tiro con arco tradicional en Teo",
    "tiro con arco tradicional en Santiago",
    "clases de tiro con arco en Teo",
    "clases de tiro con arco en Santiago de Compostela",
    "equipamento para tiro con arco en Galicia",
    "eventos de tiro con arco en Galicia",
    "eventos de tiro con arco en Santiago de Compostela"
]

previewCardImagePlacement = "top"
selfHosted = true
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = true
pagination = "10"
hideAuthor = false
description="Clube de Tiro con ArcoTeo."

   
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Avisos"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

# [[menu.main]]
#    name = "Collections"
#    url = "/collections/"
#    weight = 4

[[menu.main]]
    name = "Ferramentas"
    url = "https://arco-teo.github.io/ferramentas/"
    weight = 4

[[menu.main]]
    name = "Sobre nós"
    url = "/about/"
    weight = 5


[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"
